### ISSUE TITLE
Native build without docker?

### ISSUE THREAD

**Issue by FPSychotic** [constructiverealities/cr-dai-tools#1]
Hi, will be possible install this repository without docker?
Good initiative, thanks.

**Comment by jdavidberger** [comment]
Yes, since the repo is so new the documentation for this is a little sparse. Part of the trouble is it depends on if / which ROS you want to have support for. If you have a ROS workspace pre-existing it should be importable into that workspace in the standard way; let me know if it isn't.

If you don't want ROS integration at all its a normal cmake process.

**Comment by jdavidberger** [comment]
@FPSychotic I'm going to close this since it's been a minute with no response. There are also binaries uploaded now so maybe that answers your question too
